# SITE CONFIGURATION
title: Miguel Rojas # your site title
author: itsmiguelrojas # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://itsmiguelrojas.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Miguel Rojas
  links:
    - https://github.com/itsmiguelrojas
    - https://instagram.com/itsmiguelrojas

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Inicio', link: '/'}
  - {name: 'Categorías', link: '/categories'}
  - {name: 'Acerca de', link: '/about'}
  - {name: 'Contacto', link: '/contact'}

tagline: >
  Estudiante de biología

hero_img: posts/leaf_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: # email for form submission

twitter_username: # replace with your_twitter_username or comment to remove link from footer
github_username: itsmiguelrojas # replace with your_github_username or comment to remove link from footer
instagram_username: itsmiguelrojas # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-K39WVZQ # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 3
paginate-path: "/blog/page:num"
